### ISSUE TITLE
Cat, sed and cp errors.

### ISSUE THREAD

**Issue by yanislav-igonin** [MarechalLima/Systemd-Nvidia-Entry#14]
Hello, openning issue because some commands in scripts throws errors.

This is basic command from readme:
![screenshot from 2019-01-16 16-31-08](https://user-images.githubusercontent.com/15846431/51252302-86e90c00-19ac-11e9-991f-9f1f70ea70f9.png)

Then I tried to run it manually for Intel switch:
![screenshot from 2019-01-16 16-31-49](https://user-images.githubusercontent.com/15846431/51252357-a718cb00-19ac-11e9-9560-b24910ef3ca0.png)

And this for Nvidia switch:
![screenshot from 2019-01-16 16-32-12](https://user-images.githubusercontent.com/15846431/51252374-b6981400-19ac-11e9-9555-6d9a796d72e0.png)

Also, I've installed prime indicator. Firstly it showed nvidia icon. After I ran Setup.sh and reboot, it now showing intel. Seemingly dgpu stopped to work (in my case it's nvidia 840m), but now I can't move back to nvidia if I want to run some games in steam.

Can you help please?

**Comment by MarechalLima** [comment]
Are you utilizing grub, right? You need to use this one: https://github.com/MarechalLima/Systemd-Nvidia-Entry/releases/tag/v1-1

Could you post the output of those commands? (Just to ensure that it is okay)
`cat /etc/X11/xorg.conf.d/00-ldm.conf`
`cat /usr/lib/modprobe.d/nvidia.conf`
![image](https://user-images.githubusercontent.com/10439087/51253634-a4eb4800-197d-11e9-9053-4ffbebf259f6.png)

**Comment by yanislav-igonin** [comment]
Sorry for fullscreen screenshots, bad internet, can't now download image editor to crop.
![screenshot from 2019-01-16 17-07-27](https://user-images.githubusercontent.com/15846431/51254131-640d2680-19b1-11e9-9915-dd2f852808cb.png)

**Comment by MarechalLima** [comment]
Run this: `sudo mv /opt/Systemd-Nvidia-Entry/00-ldm.conf /etc/X11/xorg.conf.d/00-ldm.conf -f`

**Comment by yanislav-igonin** [comment]
Moved config, here output of `cat /etc/X11/xorg.conf.d/00-ldm.conf`

hobo@private ~ $ cat /etc/X11/xorg.conf.d/00-ldm.conf
Section "Module"
        Load "modesetting"
EndSection

Section "Device"
        Identifier "NVIDIA Card"
        Driver "nvidia"
        BusID "PCI:3:0:0"
        Option "AllowEmptyInitialConfiguration"
        VendorName "NVIDIA Corporation"
        BoardName "GM108M [GeForce 840M]"
EndSection

**Comment by MarechalLima** [comment]
> Moved config, here output of `cat /etc/X11/xorg.conf.d/00-ldm.conf`
> 
> hobo@private ~ $ cat /etc/X11/xorg.conf.d/00-ldm.conf
> Section "Module"
> Load "modesetting"
> EndSection
> 
> Section "Device"
> Identifier "NVIDIA Card"
> Driver "nvidia"
> BusID "PCI:3:0:0"
> Option "AllowEmptyInitialConfiguration"
> VendorName "NVIDIA Corporation"
> BoardName "GM108M [GeForce 840M]"
> EndSection

Now you should be using the Nvidia gpu

**Comment by yanislav-igonin** [comment]
I'll try it on fresh install in a few days, so I need to download latest releases of 
https://github.com/MarechalLima/Systemd-Nvidia-Entry/releases/tag/v1-1
and
https://github.com/MarechalLima/Systemd-Nvidia-Entry/releases/tag/v2-3
?

Can you explain, what I need to do step by step, please?

Also, I've installed nvidia drivers with DoFlicky, if it matters.

**Comment by MarechalLima** [comment]
> I'll try it on fresh install in a few days, so I need to download latest releases of
> https://github.com/MarechalLima/Systemd-Nvidia-Entry/releases/tag/v1-1
> and
> https://github.com/MarechalLima/Systemd-Nvidia-Entry/releases/tag/v2-3
> ?
> 
> Can you explain, what I need to do step by step, please?
> 
> Also, I've installed nvidia drivers with DoFlicky, if it matters.

Okay, I will update here what you should do, I created another branch just for the tray. And it should work on your system.

**Comment by yanislav-igonin** [comment]
Thanks a lot man, you're great!

**Comment by MarechalLima** [comment]
Clone this repository again, there is another branch: solus-prime-indicator. **Or** you can just download this zip: [solus-prime-indicator-revived.zip](https://github.com/MarechalLima/Systemd-Nvidia-Entry/files/2765096/solus-prime-indicator-revived.zip)

First you need to run this script to ensure that things are as they should: [safeStart.zip](https://github.com/MarechalLima/Systemd-Nvidia-Entry/files/2765047/safeStart.zip)

This branch has things working (I zipped it): [solus-prime-indicator](https://github.com/MarechalLima/Systemd-Nvidia-Entry/tree/solus-prime-indicator)
To Install: bash Setup.sh
To Uninstall: bash Setup.sh rm
![image](https://user-images.githubusercontent.com/10439087/51262616-78d9c200-1991-11e9-94af-dcaea11d7c2c.png)

That prime indicator has a menu, and is through there that you should change between cards.
![image](https://user-images.githubusercontent.com/10439087/51262909-09b09d80-1992-11e9-903b-077be1473b77.png)

**Comment by MarechalLima** [comment]
Also, if after a system upgrade something is not right, just reboot: there is a script that runs at startup to ensure that things are right. As described in #11 , it would be better handled by some hook like in arch, but I don't know of similar tool in Solus.

**Comment by yanislav-igonin** [comment]
@MarechalLima reinstalled solus yesterday, install drivers, use scripts, all works fine. Tested games on nvidia and battery save on intel.
Thanks again for the help, you rock!
